### ISSUE TITLE
[MacOS] Add Icon to Application

### ISSUE THREAD

**Issue by WingofaGriffin** [ryandavidmercado/emu-hub#18]
Currently only the generic Electron icon is used. Add some flair even with a hand drawn icon to make it unique!

**Comment by CHJ85** [comment]
In the meantime, what you can do is just download the icon and drag the image to the electron icon in the app's "get info" box. That'll replace the icon.

**Comment by rhythmerc** [comment]
Resolved in Beta 2 (though the centering debate still carries on, eternal)
