### ISSUE TITLE
External Keyboard Support for Input Modals

### ISSUE THREAD

**Issue by WingofaGriffin** [ryandavidmercado/emu-hub#19]
For selecting my file directory for my ROMS folder, I was forced to use the on screen keyboard and click. Please add support for external keyboards and even better OS based menu selection for directory selection

**Comment by rhythmerc** [comment]
@WingofaGriffin native keyboard support solved in https://github.com/ryandavidmercado/emu-hub/pull/37!
Opened a new issue for having a directory selector flow: https://github.com/ryandavidmercado/emu-hub/issues/36
