### ISSUE TITLE
Swap Emulator Defaults Option

### ISSUE THREAD

**Issue by WingofaGriffin** [ryandavidmercado/emu-hub#21]
Doesn't seem to be a clear way in the UI to see which defaults are set and how to change them. I know adding more is a WIP, but i feel like we are lacking some clarity.

**Comment by rhythmerc** [comment]
PR ready! Feel free to review

https://github.com/ryandavidmercado/emu-hub/pull/23

**Comment by rhythmerc** [comment]
Closing; [merged into 1.0.0-beta.2](https://github.com/ryandavidmercado/emu-hub/pull/23)
