### ISSUE TITLE
Is support for ARM on the roadmap?

### ISSUE THREAD

**Issue by ttang4299** [ryandavidmercado/emu-hub#24]
I'd love to see support for both ARM Linux handhelds such as Anbernic and PowKiddy, and Android as well. It would be convenient to see this addressed in a FAQ even if this isn't on the roadmap.

**Comment by WingofaGriffin** [comment]
> I'd love to see support for both ARM Linux handhelds such as Anbernic and PowKiddy, and Android as well. It would be convenient to see this addressed in a FAQ even if this isn't on the roadmap.

this already works for ARM based macs, so I assume it is possible and simply needs a few tweaks (and of course, testing). Should be easy to test on something like a Raspberry Pi @ryandavidmercado

**Comment by rhythmerc** [comment]
@ttang4299 don't have a Linux ARM machine to test on but I can run some builds for testing!

**Comment by rhythmerc** [comment]
@ttang4299 got some experimental ARM builds up for Beta 2! These are untested so I can't make any guarantees but please feel free to give them a go:

https://github.com/ryandavidmercado/emu-hub/releases/tag/v1.0.0-beta.2
