### ISSUE TITLE
Feature Request: Recursive directory ROM scanning

### ISSUE THREAD

**Issue by MasterRee** [ryandavidmercado/emu-hub#28]
Like many users, my ROMs are organized into subdirectories and not in the root of a single directory. Unless I missed something, I can only specify a single directory for my ROMs and it is not detecting any of the ROMs that I have divided into subdirectories by system. This change would be a significant usability improvement.

**Comment by rhythmerc** [comment]
Hey @MasterRee ! We support nested subdirectories but games do have to be organized by the system folders that EmuHub generates at the top folder level (for example, EMUHUB_ROMS/ps2/my/nested/ps2game.iso). Are you using the system folders generated by EmuHub or are these differently-named folders you've brought in?

Alternatively you can add entries like:

``` yaml
- id: ps2
  romdir: "/path/to/PlayStation 2 Folder"
```

to the systems.yml file in EmuHubConfig (file path for this is in the README!)

**Comment by MasterRee** [comment]
I have an existing folder structure that is /ROMs/PS2/Game.chd. Sorry if I missed the customization option in the README. I'll look at it again. Glad to know I can customize the directory names EmuHub will expect and that it can do recursive searches. Thanks!

**Comment by rhythmerc** [comment]
No problem! System/emulators section in the README only has a walkthrough for adding new ones with a brief blurb on extending/overriding built-ins; README definitely needs a dedicated section for this topic. Lmk if you run into any problems!
